const mongoose = require('mongoose');

const taskSchema = new mongoose.Schema({
  id: { type: String, required: true },
  text: { type: String, required: true },
  type: { type: String, enum: ['problem', 'revision', 'concept', 'contest', 'read'], default: 'problem' },
  platform: { type: String, default: '' },
  link: { type: String, default: '' },
  isCompleted: { type: Boolean, default: false },
  priority: { type: String, enum: ['high', 'medium', 'low'], default: 'medium' },
  estimatedMinutes: { type: Number, default: 30 },
  completedAt: { type: Date },
}, { _id: false });

const todoPlanSchema = new mongoose.Schema({
  userId: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true, index: true },
  date: { type: Date, required: true },
  title: { type: String, default: "Today's Plan" },
  tasks: [taskSchema],
  isAutoGenerated: { type: Boolean, default: false },
  aiGenerated: { type: Boolean, default: false },
  notes: { type: String, default: '' },
}, { timestamps: true });

todoPlanSchema.index({ userId: 1, date: 1 }, { unique: true });

// Virtual: completion percentage
todoPlanSchema.virtual('completionPercent').get(function () {
  if (!this.tasks.length) return 0;
  return Math.round((this.tasks.filter(t => t.isCompleted).length / this.tasks.length) * 100);
});

module.exports = mongoose.model('TodoPlan', todoPlanSchema);
