import 'dart:async';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:go_router/go_router.dart';
import '../bloc/notes_bloc.dart';
import '../data/notes_repository.dart';
import '../../../core/theme/app_theme.dart';
import '../../../shared/services/api_service.dart';
import '../../../core/di/service_locator.dart';

// ─── DSA Template ─────────────────────────────────────────────────
const kDsaTemplate = '''# Problem Title

## Problem Statement
Describe the problem here.

## Intuition
What is the main idea?

## Approach
Step by step explanation:
1. 
2. 
3. 

## Dry Run
Example walkthrough:

## Code
```cpp

```

## Time Complexity
O( )

## Space Complexity
O( )

## Similar Problems
- 
''';

const kMeetingTemplate = '''# Meeting / Lecture Notes

📅 Date: 
👥 Attendees: 

## Key Points
- 
- 

## Action Items
- [ ] 
- [ ] 

## Follow-ups
- 

## Notes
''';

const kSnippetTemplate = '''// Title: 
// Language: 
// Purpose: 

```

```

// Usage:

// Notes:
''';

const kStudyTemplate = '''# Study Note — Topic Name

## Overview
Brief description of the topic.

## Key Concepts
1. 
2. 
3. 

## Examples

## Practice Problems
- [ ] 
- [ ] 

## Resources
- 

## Summary
''';

const kQuickTemplate = '';
const kDailyTemplate = ''; // generated by backend

// ─── Note Editor Screen ───────────────────────────────────────────
class NoteEditorScreen extends StatefulWidget {
  final String? noteId;
  final String? initialNoteType;
  const NoteEditorScreen({super.key, this.noteId, this.initialNoteType});
  @override State<NoteEditorScreen> createState() => _NoteEditorScreenState();
}

class _NoteEditorScreenState extends State<NoteEditorScreen> with SingleTickerProviderStateMixin {
  final _titleCtrl = TextEditingController();
  final _contentCtrl = TextEditingController();
  final _tagsCtrl = TextEditingController();
  final _folderCtrl = TextEditingController();
  final _chatCtrl = TextEditingController();
  final ScrollController _chatScrollCtrl = ScrollController();
  late TabController _panelTab;

  String _color = 'default';
  String _noteType = 'quick';
  String _collection = 'General';
  bool _isPinned = false;
  bool _isFavorited = false;
  bool _loading = false;
  bool _saving = false;
  bool _previewMode = false;
  int _wordCount = 0;

  // AI state
  bool _aiLoading = false;
  String _aiAction = '';
  String _aiResponse = '';
  List<Map<String, dynamic>> _flashcards = [];
  List<Map<String, dynamic>> _quiz = [];
  List<Map<String, dynamic>> _chatHistory = [];
  String _roadmap = '';
  int _flashcardIndex = 0;
  bool _flashcardFlipped = false;
  int _quizIndex = 0;
  String? _quizSelected;
  bool _quizShowAnswer = false;
  Timer? _autoSaveTimer;

  final List<String> _colors = ['default', 'red', 'blue', 'green', 'purple', 'orange', 'yellow', 'pink', 'teal'];
  final List<String> _collections = ['General', 'DSA', 'Flutter', 'Linux', 'ServiceNow', 'Azure', 'Interview Prep', 'Personal Journal'];

  @override
  void initState() {
    super.initState();
    _panelTab = TabController(length: 4, vsync: this);
    _noteType = widget.initialNoteType ?? 'quick';
    if (widget.noteId != null) {
      _loadNote();
    } else {
      _folderCtrl.text = 'General';
      _applyTemplate(_noteType);
    }
    _contentCtrl.addListener(_onContentChanged);
  }

  void _onContentChanged() {
    final words = _contentCtrl.text.trim().split(RegExp(r'\s+')).where((w) => w.isNotEmpty).length;
    if (words != _wordCount) setState(() => _wordCount = words);
    _autoSaveTimer?.cancel();
    _autoSaveTimer = Timer(const Duration(seconds: 3), () { if (widget.noteId != null) _saveNote(silent: true); });
  }

  void _applyTemplate(String type) {
    switch (type) {
      case 'dsa': _contentCtrl.text = kDsaTemplate; break;
      case 'meeting': _contentCtrl.text = kMeetingTemplate; break;
      case 'snippet': _contentCtrl.text = kSnippetTemplate; break;
      case 'study': _contentCtrl.text = kStudyTemplate; break;
      default: break;
    }
  }

  @override
  void dispose() {
    _autoSaveTimer?.cancel();
    _titleCtrl.dispose();
    _contentCtrl.dispose();
    _tagsCtrl.dispose();
    _folderCtrl.dispose();
    _chatCtrl.dispose();
    _chatScrollCtrl.dispose();
    _panelTab.dispose();
    super.dispose();
  }

  Future<void> _loadNote() async {
    setState(() => _loading = true);
    try {
      final note = await sl<NotesRepository>().getNote(widget.noteId!);
      setState(() {
        _titleCtrl.text = note['title'] ?? '';
        _contentCtrl.text = note['contentText'] ?? '';
        _folderCtrl.text = note['folderPath'] ?? 'General';
        _color = note['color'] ?? 'default';
        _noteType = note['noteType'] ?? 'quick';
        _collection = note['collection'] ?? 'General';
        _isPinned = note['isPinned'] ?? false;
        _isFavorited = note['isFavorited'] ?? false;
        _tagsCtrl.text = List<String>.from(note['tags'] ?? []).join(', ');
        _flashcards = List<Map<String, dynamic>>.from(note['flashcards'] ?? []);
        _quiz = List<Map<String, dynamic>>.from(note['quiz'] ?? []);
        _roadmap = note['aiRoadmap'] ?? '';
        _chatHistory = List<Map<String, dynamic>>.from(note['aiChatHistory'] ?? []);
      });
    } catch (e) {
      if (mounted) ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('Error: $e'), backgroundColor: AppColors.danger));
    } finally {
      setState(() => _loading = false);
    }
  }

  Future<void> _saveNote({bool silent = false}) async {
    if (_titleCtrl.text.trim().isEmpty && !silent) {
      ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Please enter a title'), backgroundColor: AppColors.warning));
      return;
    }
    if (silent && _titleCtrl.text.trim().isEmpty) return;

    setState(() => _saving = true);
    final tags = _tagsCtrl.text.split(',').map((t) => t.trim()).where((t) => t.isNotEmpty).toList();
    final contentDelta = {'ops': [{'insert': _contentCtrl.text}]};
    final data = {
      'title': _titleCtrl.text.trim().isEmpty ? 'Untitled' : _titleCtrl.text.trim(),
      'content': contentDelta,
      'folder': _folderCtrl.text.trim(),
      'folderPath': _folderCtrl.text.trim(),
      'collection': _collection,
      'tags': tags,
      'color': _color,
      'isPinned': _isPinned,
      'isFavorited': _isFavorited,
      'noteType': _noteType,
    };
    try {
      if (widget.noteId != null) {
        await sl<NotesRepository>().updateNote(widget.noteId!, data);
      } else {
        await sl<NotesRepository>().createNote(data);
      }
      if (mounted) {
        context.read<NotesBloc>().add(const NotesLoadRequested());
        if (!silent) context.pop();
      }
    } catch (e) {
      if (mounted && !silent) ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('Error: $e'), backgroundColor: AppColors.danger));
    } finally {
      setState(() => _saving = false);
    }
  }

  Future<void> _runAiAction(String action) async {
    final content = _contentCtrl.text.trim();
    if (content.isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Write some content first'), backgroundColor: AppColors.warning));
      return;
    }
    if (widget.noteId == null) {
      ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Save the note first'), backgroundColor: AppColors.warning));
      return;
    }

    setState(() { _aiLoading = true; _aiAction = action; _aiResponse = ''; });

    try {
      switch (action) {
        case 'flashcards':
          final cards = await sl<NotesRepository>().generateFlashcards(widget.noteId!);
          setState(() { _flashcards = cards; _flashcardIndex = 0; _flashcardFlipped = false; _panelTab.index = 1; });
          break;
        case 'quiz':
          final q = await sl<NotesRepository>().generateQuiz(widget.noteId!);
          setState(() { _quiz = q; _quizIndex = 0; _quizSelected = null; _quizShowAnswer = false; _panelTab.index = 2; });
          break;
        case 'roadmap':
          final r = await sl<NotesRepository>().generateRoadmap(widget.noteId!);
          setState(() { _roadmap = r; _panelTab.index = 3; });
          break;
        case 'autotag':
          final result = await sl<NotesRepository>().autoTag(widget.noteId!);
          if (result['title'] != null && result['title'] != _titleCtrl.text) {
            setState(() {
              _titleCtrl.text = result['title'];
              final newTags = List<String>.from(result['tags'] ?? []);
              _tagsCtrl.text = newTags.join(', ');
            });
            if (mounted) ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('✨ Title and tags updated by AI!'), backgroundColor: AppColors.success));
          }
          break;
        case 'revision':
          await sl<NotesRepository>().scheduleRevision(widget.noteId!);
          if (mounted) ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('📅 Revision schedule set! 1, 3, 7, 30 days'), backgroundColor: AppColors.success));
          break;
        default:
          final res = await sl<ApiService>().post('/ai/notes-assistant', data: {'action': action, 'content': content});
          final result = res.data['result'];
          if (result is List) {
            _aiResponse = result.map((item) {
              if (item is Map && item.containsKey('question')) return 'Q: ${item['question']}\nA: ${item['answer']}';
              return item.toString();
            }).join('\n\n');
          } else {
            _aiResponse = result.toString();
          }
          _panelTab.index = 0;
      }
    } catch (e) {
      if (mounted) ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('AI Error: $e'), backgroundColor: AppColors.danger));
    } finally {
      setState(() => _aiLoading = false);
    }
  }

  Future<void> _sendChatMessage() async {
    final msg = _chatCtrl.text.trim();
    if (msg.isEmpty) return;
    if (widget.noteId == null) {
      ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Save the note first to chat about it'), backgroundColor: AppColors.warning));
      return;
    }
    _chatCtrl.clear();
    setState(() {
      _chatHistory.add({'role': 'user', 'content': msg});
      _aiLoading = true;
    });
    try {
      final reply = await sl<NotesRepository>().aiChat(widget.noteId!, msg);
      setState(() { _chatHistory.add({'role': 'assistant', 'content': reply}); });
      await Future.delayed(const Duration(milliseconds: 100));
      if (_chatScrollCtrl.hasClients) _chatScrollCtrl.animateTo(_chatScrollCtrl.position.maxScrollExtent, duration: const Duration(milliseconds: 300), curve: Curves.easeOut);
    } catch (e) {
      setState(() { _chatHistory.add({'role': 'assistant', 'content': 'Error: $e'}); });
    } finally {
      setState(() => _aiLoading = false);
    }
  }

  void _insertText(String prefix, String suffix) {
    final text = _contentCtrl.text;
    final sel = _contentCtrl.selection;
    if (sel.isValid) {
      final selected = sel.textInside(text);
      final newText = text.replaceRange(sel.start, sel.end, '$prefix$selected$suffix');
      _contentCtrl.value = TextEditingValue(text: newText, selection: TextSelection.collapsed(offset: sel.start + prefix.length + selected.length + suffix.length));
    } else {
      final off = text.length;
      _contentCtrl.value = TextEditingValue(text: '$text$prefix$suffix', selection: TextSelection.collapsed(offset: off + prefix.length));
    }
  }

  Color _colorHex(String name) {
    const m = {'red': Colors.redAccent, 'blue': Colors.blueAccent, 'green': Colors.greenAccent, 'purple': Colors.purpleAccent, 'orange': Colors.orangeAccent, 'yellow': Colors.yellowAccent, 'pink': Colors.pinkAccent, 'teal': Colors.tealAccent};
    return m[name] ?? AppColors.darkCard;
  }

  @override
  Widget build(BuildContext context) {
    if (_loading) return const Scaffold(backgroundColor: AppColors.darkBg, body: Center(child: CircularProgressIndicator(color: AppColors.primary)));
    final isWide = MediaQuery.of(context).size.width > 700;

    return Scaffold(
      backgroundColor: AppColors.darkBg,
      appBar: _buildAppBar(),
      body: isWide
          ? Row(children: [
              Expanded(flex: 3, child: _buildEditor()),
              Container(width: 340, decoration: const BoxDecoration(border: Border(left: BorderSide(color: AppColors.darkBorder))), child: _buildAiPanel()),
            ])
          : Column(children: [Expanded(child: _buildEditor())]),
      bottomNavigationBar: isWide ? _buildStatusBar() : _buildMobileBottom(),
    );
  }

  PreferredSizeWidget _buildAppBar() {
    return AppBar(
      backgroundColor: AppColors.darkBg,
      elevation: 0,
      leading: IconButton(icon: const Icon(Icons.arrow_back, color: Colors.white), onPressed: () => context.pop()),
      title: Row(
        children: [
          _buildTypeSelector(),
          const SizedBox(width: 8),
          Expanded(
            child: TextField(
              controller: _titleCtrl,
              style: const TextStyle(color: Colors.white, fontSize: 16, fontWeight: FontWeight.w700),
              decoration: const InputDecoration(hintText: 'Note title...', hintStyle: TextStyle(color: Colors.white38), border: InputBorder.none, isDense: true),
            ),
          ),
        ],
      ),
      actions: [
        IconButton(icon: Icon(_isFavorited ? Icons.star_rounded : Icons.star_border_rounded, color: _isFavorited ? const Color(0xFFFFB300) : Colors.white54), onPressed: () => setState(() => _isFavorited = !_isFavorited), tooltip: 'Favorite'),
        IconButton(icon: Icon(_isPinned ? Icons.push_pin_rounded : Icons.push_pin_outlined, color: _isPinned ? AppColors.primary : Colors.white54), onPressed: () => setState(() => _isPinned = !_isPinned), tooltip: 'Pin'),
        IconButton(icon: Icon(_previewMode ? Icons.edit_rounded : Icons.preview_rounded, color: Colors.white70), onPressed: () => setState(() => _previewMode = !_previewMode), tooltip: _previewMode ? 'Edit' : 'Preview'),
        IconButton(
          icon: _saving ? const SizedBox(width: 18, height: 18, child: CircularProgressIndicator(strokeWidth: 2, color: Colors.white)) : const Icon(Icons.check_rounded, color: Colors.white),
          onPressed: _saving ? null : () => _saveNote(),
          tooltip: 'Save',
        ),
      ],
    );
  }

  Widget _buildTypeSelector() {
    const types = {'quick': '⚡', 'dsa': '🧠', 'daily': '📅', 'snippet': '💻', 'meeting': '📋', 'study': '📚'};
    return GestureDetector(
      onTap: () => showDialog(
        context: context,
        builder: (ctx) => AlertDialog(
          backgroundColor: const Color(0xFF1E1E2E),
          title: const Text('Note Type', style: TextStyle(color: Colors.white)),
          content: Wrap(
            spacing: 8, runSpacing: 8,
            children: types.entries.map((e) => GestureDetector(
              onTap: () { setState(() => _noteType = e.key); Navigator.pop(ctx); },
              child: Container(
                width: 80, height: 60,
                decoration: BoxDecoration(color: _noteType == e.key ? AppColors.primary.withValues(alpha: 0.2) : const Color(0xFF1A1A2E), borderRadius: BorderRadius.circular(10), border: Border.all(color: _noteType == e.key ? AppColors.primary : AppColors.darkBorder)),
                child: Column(mainAxisAlignment: MainAxisAlignment.center, children: [
                  Text(e.value, style: const TextStyle(fontSize: 20)),
                  Text(e.key, style: const TextStyle(color: Colors.white60, fontSize: 9)),
                ]),
              ),
            )).toList(),
          ),
        ),
      ),
      child: Container(
        padding: const EdgeInsets.all(6),
        decoration: BoxDecoration(color: AppColors.primary.withValues(alpha: 0.1), borderRadius: BorderRadius.circular(8)),
        child: Text(types[_noteType] ?? '📝', style: const TextStyle(fontSize: 20)),
      ),
    );
  }

  Widget _buildEditor() {
    return SingleChildScrollView(
      padding: const EdgeInsets.all(16),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // Metadata row
          Row(
            children: [
              const Icon(Icons.folder_rounded, size: 14, color: AppColors.darkTextSecondary),
              const SizedBox(width: 4),
              Expanded(child: TextField(controller: _folderCtrl, style: const TextStyle(color: Colors.white70, fontSize: 12), decoration: const InputDecoration(hintText: 'Folder path', hintStyle: TextStyle(color: Colors.white24, fontSize: 12), border: InputBorder.none, isDense: true))),
              const SizedBox(width: 8),
              DropdownButton<String>(
                value: _collection,
                dropdownColor: const Color(0xFF1E1E2E),
                style: const TextStyle(color: Colors.white70, fontSize: 12),
                underline: const SizedBox(),
                items: _collections.map((c) => DropdownMenuItem(value: c, child: Text(c))).toList(),
                onChanged: (v) => setState(() => _collection = v!),
              ),
            ],
          ),
          Row(
            children: [
              const Icon(Icons.tag_rounded, size: 14, color: AppColors.darkTextSecondary),
              const SizedBox(width: 4),
              Expanded(child: TextField(controller: _tagsCtrl, style: const TextStyle(color: Colors.white70, fontSize: 12), decoration: const InputDecoration(hintText: 'Tags (comma-separated)', hintStyle: TextStyle(color: Colors.white24, fontSize: 12), border: InputBorder.none, isDense: true))),
              GestureDetector(
                onTap: () => _runAiAction('autotag'),
                child: Container(padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4), decoration: BoxDecoration(color: AppColors.accent.withValues(alpha: 0.1), borderRadius: BorderRadius.circular(6)), child: const Row(children: [Icon(Icons.auto_awesome, size: 12, color: AppColors.accent), SizedBox(width: 4), Text('Auto-tag', style: TextStyle(color: AppColors.accent, fontSize: 11))])),
              ),
            ],
          ),
          // Color selector
          Row(
            children: [
              const Text('Color:', style: TextStyle(color: AppColors.darkTextSecondary, fontSize: 12)),
              const SizedBox(width: 8),
              ..._colors.map((c) => GestureDetector(
                onTap: () => setState(() => _color = c),
                child: Container(margin: const EdgeInsets.only(right: 6), width: 18, height: 18, decoration: BoxDecoration(color: _colorHex(c), shape: BoxShape.circle, border: Border.all(color: _color == c ? Colors.white : Colors.transparent, width: 2))),
              )),
            ],
          ),
          const SizedBox(height: 10),
          const Divider(color: AppColors.darkBorder, height: 1),
          // Formatting toolbar
          _buildToolbar(),
          const Divider(color: AppColors.darkBorder, height: 1),
          const SizedBox(height: 12),
          // Editor / Preview
          if (_previewMode)
            _buildMarkdownPreview()
          else
            TextField(
              controller: _contentCtrl,
              maxLines: null,
              minLines: 20,
              style: const TextStyle(color: Colors.white, fontSize: 14, height: 1.7, fontFamily: 'monospace'),
              decoration: const InputDecoration(hintText: 'Start writing...', hintStyle: TextStyle(color: Colors.white24), border: InputBorder.none),
            ),
        ],
      ),
    );
  }

  Widget _buildToolbar() {
    return SingleChildScrollView(
      scrollDirection: Axis.horizontal,
      child: Row(
        children: [
          IconButton(icon: const Icon(Icons.format_bold_rounded, size: 18), onPressed: () => _insertText('**', '**'), tooltip: 'Bold', color: Colors.white70),
          IconButton(icon: const Icon(Icons.format_italic_rounded, size: 18), onPressed: () => _insertText('*', '*'), tooltip: 'Italic', color: Colors.white70),
          IconButton(icon: const Icon(Icons.format_underlined, size: 18), onPressed: () => _insertText('__', '__'), tooltip: 'Underline', color: Colors.white70),
          IconButton(icon: const Icon(Icons.code_rounded, size: 18), onPressed: () => _insertText('`', '`'), tooltip: 'Inline Code', color: Colors.white70),
          IconButton(icon: const Icon(Icons.integration_instructions_outlined, size: 18), onPressed: () => _insertText('\n```\n', '\n```\n'), tooltip: 'Code Block', color: Colors.white70),
          IconButton(icon: const Icon(Icons.format_list_bulleted, size: 18), onPressed: () => _insertText('\n- ', ''), tooltip: 'Bullet', color: Colors.white70),
          IconButton(icon: const Icon(Icons.check_box_outlined, size: 18), onPressed: () => _insertText('\n- [ ] ', ''), tooltip: 'Checklist', color: Colors.white70),
          IconButton(icon: const Icon(Icons.format_list_numbered, size: 18), onPressed: () => _insertText('\n1. ', ''), tooltip: 'Numbered', color: Colors.white70),
          IconButton(icon: const Icon(Icons.format_quote, size: 18), onPressed: () => _insertText('\n> ', ''), tooltip: 'Quote', color: Colors.white70),
          IconButton(icon: const Icon(Icons.horizontal_rule, size: 18), onPressed: () => _insertText('\n---\n', ''), tooltip: 'Divider', color: Colors.white70),
          Container(width: 1, height: 24, color: AppColors.darkBorder, margin: const EdgeInsets.symmetric(horizontal: 4)),
          IconButton(icon: const Icon(Icons.copy_all_rounded, size: 18, color: AppColors.accent), onPressed: () { Clipboard.setData(ClipboardData(text: _contentCtrl.text)); ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Copied!'), duration: Duration(seconds: 1))); }, tooltip: 'Copy All'),
        ],
      ),
    );
  }

  Widget _buildMarkdownPreview() {
    final lines = _contentCtrl.text.split('\n');
    return Container(
      padding: const EdgeInsets.all(12),
      decoration: BoxDecoration(color: const Color(0xFF0D0D1A), borderRadius: BorderRadius.circular(12)),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: lines.map((line) {
          if (line.startsWith('# ')) return Padding(padding: const EdgeInsets.only(bottom: 8, top: 12), child: Text(line.substring(2), style: const TextStyle(color: Colors.white, fontSize: 22, fontWeight: FontWeight.w800)));
          if (line.startsWith('## ')) return Padding(padding: const EdgeInsets.only(bottom: 6, top: 8), child: Text(line.substring(3), style: const TextStyle(color: Colors.white, fontSize: 18, fontWeight: FontWeight.w700)));
          if (line.startsWith('### ')) return Padding(padding: const EdgeInsets.only(bottom: 4, top: 6), child: Text(line.substring(4), style: const TextStyle(color: AppColors.primary, fontSize: 15, fontWeight: FontWeight.w600)));
          if (line.startsWith('- [ ] ')) return Row(children: [Checkbox(value: false, onChanged: (_) {}, fillColor: WidgetStateProperty.all(AppColors.darkCard)), Text(line.substring(6), style: const TextStyle(color: Colors.white70, fontSize: 14))]);
          if (line.startsWith('- [x] ')) return Row(children: [Checkbox(value: true, onChanged: (_) {}, fillColor: WidgetStateProperty.all(AppColors.primary)), Text(line.substring(6), style: const TextStyle(color: Colors.white54, fontSize: 14, decoration: TextDecoration.lineThrough))]);
          if (line.startsWith('- ')) return Padding(padding: const EdgeInsets.only(bottom: 2), child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [const Text('• ', style: TextStyle(color: AppColors.accent, fontSize: 14)), Expanded(child: Text(line.substring(2), style: const TextStyle(color: Colors.white70, fontSize: 14)))]));
          if (line.startsWith('> ')) return Container(margin: const EdgeInsets.only(bottom: 4), padding: const EdgeInsets.fromLTRB(12, 4, 4, 4), decoration: const BoxDecoration(border: Border(left: BorderSide(color: AppColors.primary, width: 3))), child: Text(line.substring(2), style: const TextStyle(color: Colors.white60, fontStyle: FontStyle.italic)));
          if (line.trim() == '---') return const Divider(color: AppColors.darkBorder, height: 24);
          if (line.startsWith('```')) return Container(margin: const EdgeInsets.only(bottom: 4), padding: const EdgeInsets.all(8), decoration: BoxDecoration(color: Colors.black, borderRadius: BorderRadius.circular(6)), child: Text(line, style: const TextStyle(color: Colors.greenAccent, fontSize: 12, fontFamily: 'monospace')));
          return Padding(padding: const EdgeInsets.only(bottom: 2), child: Text(line, style: const TextStyle(color: Colors.white70, fontSize: 14, height: 1.5)));
        }).toList(),
      ),
    );
  }

  Widget _buildAiPanel() {
    return Column(
      children: [
        // AI Panel Tabs
        Container(
          color: const Color(0xFF0D0D1A),
          child: TabBar(
            controller: _panelTab,
            labelColor: AppColors.accent,
            unselectedLabelColor: Colors.white38,
            indicatorColor: AppColors.accent,
            indicatorSize: TabBarIndicatorSize.label,
            labelStyle: const TextStyle(fontSize: 11, fontWeight: FontWeight.w600),
            tabs: const [Tab(text: '🤖 AI'), Tab(text: '🃏 Cards'), Tab(text: '❓ Quiz'), Tab(text: '🗺️ Roadmap')],
          ),
        ),
        Expanded(
          child: TabBarView(
            controller: _panelTab,
            children: [
              _buildAiActionsTab(),
              _buildFlashcardsTab(),
              _buildQuizTab(),
              _buildRoadmapTab(),
            ],
          ),
        ),
      ],
    );
  }

  Widget _buildAiActionsTab() {
    return Column(
      children: [
        // AI Action Buttons
        Container(
          padding: const EdgeInsets.all(12),
          child: Wrap(
            spacing: 6, runSpacing: 6,
            children: [
              _aiBtn('✨ Summarize', 'summarize'),
              _aiBtn('🃏 Flashcards', 'flashcards'),
              _aiBtn('❓ Quiz', 'quiz'),
              _aiBtn('🗺️ Roadmap', 'roadmap'),
              _aiBtn('💡 Explain', 'explain'),
              _aiBtn('⏱️ Complexity', 'complexity'),
              _aiBtn('🐛 Fix Bugs', 'fix'),
              _aiBtn('🏷️ Auto-tag', 'autotag'),
              _aiBtn('📅 Schedule Review', 'revision'),
            ],
          ),
        ),
        const Divider(color: AppColors.darkBorder, height: 1),
        // AI Chat
        Expanded(
          child: Column(
            children: [
              Padding(
                padding: const EdgeInsets.fromLTRB(12, 8, 12, 0),
                child: Row(
                  children: [
                    const Icon(Icons.chat_bubble_outline_rounded, size: 14, color: AppColors.accent),
                    const SizedBox(width: 6),
                    const Text('Chat About This Note', style: TextStyle(color: Colors.white70, fontSize: 12, fontWeight: FontWeight.w600)),
                    if (_aiLoading && _aiAction == '') ...[const SizedBox(width: 8), const SizedBox(width: 12, height: 12, child: CircularProgressIndicator(strokeWidth: 2, color: AppColors.accent))],
                  ],
                ),
              ),
              Expanded(
                child: _chatHistory.isEmpty
                    ? const Center(child: Text('Ask anything about\nyour note!', textAlign: TextAlign.center, style: TextStyle(color: Colors.white38, fontSize: 13)))
                    : ListView.builder(
                        controller: _chatScrollCtrl,
                        padding: const EdgeInsets.all(12),
                        itemCount: _chatHistory.length,
                        itemBuilder: (_, i) {
                          final msg = _chatHistory[i];
                          final isUser = msg['role'] == 'user';
                          return Align(
                            alignment: isUser ? Alignment.centerRight : Alignment.centerLeft,
                            child: Container(
                              margin: const EdgeInsets.only(bottom: 8),
                              padding: const EdgeInsets.all(10),
                              constraints: const BoxConstraints(maxWidth: 240),
                              decoration: BoxDecoration(
                                color: isUser ? AppColors.primary.withValues(alpha: 0.2) : const Color(0xFF1A1A2E),
                                borderRadius: BorderRadius.circular(12),
                                border: Border.all(color: isUser ? AppColors.primary.withValues(alpha: 0.4) : AppColors.darkBorder),
                              ),
                              child: Text(msg['content'] ?? '', style: TextStyle(color: isUser ? Colors.white : Colors.white70, fontSize: 12, height: 1.4)),
                            ),
                          );
                        },
                      ),
              ),
              // Chat input
              Container(
                padding: const EdgeInsets.all(8),
                decoration: const BoxDecoration(border: Border(top: BorderSide(color: AppColors.darkBorder))),
                child: Row(
                  children: [
                    Expanded(child: TextField(controller: _chatCtrl, style: const TextStyle(color: Colors.white, fontSize: 13), decoration: const InputDecoration(hintText: 'Ask about this note...', hintStyle: TextStyle(color: Colors.white38, fontSize: 12), border: InputBorder.none, contentPadding: EdgeInsets.symmetric(horizontal: 8, vertical: 6)), maxLines: null, onSubmitted: (_) => _sendChatMessage())),
                    IconButton(icon: const Icon(Icons.send_rounded, size: 18, color: AppColors.accent), onPressed: _sendChatMessage),
                  ],
                ),
              ),
            ],
          ),
        ),
        // AI response box
        if (_aiResponse.isNotEmpty && !_aiLoading)
          Container(
            height: 160,
            margin: const EdgeInsets.all(8),
            padding: const EdgeInsets.all(10),
            decoration: BoxDecoration(color: const Color(0xFF0D0D1A), borderRadius: BorderRadius.circular(10), border: Border.all(color: AppColors.accent.withValues(alpha: 0.3))),
            child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
              Row(children: [
                const Text('AI Result', style: TextStyle(color: AppColors.accent, fontSize: 11, fontWeight: FontWeight.w600)),
                const Spacer(),
                GestureDetector(onTap: () { setState(() { _contentCtrl.text += '\n\n---\n### AI Insights\n$_aiResponse'; _aiResponse = ''; }); }, child: const Icon(Icons.add_circle_outline_rounded, size: 16, color: AppColors.accent)),
              ]),
              const SizedBox(height: 4),
              Expanded(child: SingleChildScrollView(child: Text(_aiResponse, style: const TextStyle(color: Colors.white70, fontSize: 11, height: 1.4)))),
            ]),
          ),
        if (_aiLoading)
          Container(
            margin: const EdgeInsets.all(8),
            padding: const EdgeInsets.all(16),
            child: Column(children: [
              const CircularProgressIndicator(color: AppColors.accent, strokeWidth: 2),
              const SizedBox(height: 8),
              Text('AI is working on ${_aiAction.toUpperCase()}...', style: const TextStyle(color: AppColors.accent, fontSize: 11)),
            ]),
          ),
      ],
    );
  }

  Widget _aiBtn(String label, String action) {
    final isActive = _aiAction == action && _aiLoading;
    return GestureDetector(
      onTap: () => _runAiAction(action),
      child: Container(
        padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 6),
        decoration: BoxDecoration(
          color: isActive ? AppColors.accent.withValues(alpha: 0.2) : const Color(0xFF1A1A2E),
          borderRadius: BorderRadius.circular(20),
          border: Border.all(color: isActive ? AppColors.accent : AppColors.darkBorder),
        ),
        child: Text(label, style: TextStyle(color: isActive ? AppColors.accent : Colors.white60, fontSize: 11, fontWeight: FontWeight.w600)),
      ),
    );
  }

  Widget _buildFlashcardsTab() {
    if (_flashcards.isEmpty) {
      return Center(
        child: Column(mainAxisAlignment: MainAxisAlignment.center, children: [
          const Text('🃏', style: TextStyle(fontSize: 48)),
          const SizedBox(height: 12),
          const Text('No flashcards yet', style: TextStyle(color: Colors.white, fontSize: 16)),
          const SizedBox(height: 8),
          ElevatedButton.icon(onPressed: () => _runAiAction('flashcards'), icon: const Icon(Icons.auto_awesome), label: const Text('Generate Flashcards'), style: ElevatedButton.styleFrom(backgroundColor: AppColors.primary)),
        ]),
      );
    }
    final card = _flashcards[_flashcardIndex];
    return Padding(
      padding: const EdgeInsets.all(16),
      child: Column(
        children: [
          Text('${_flashcardIndex + 1} / ${_flashcards.length}', style: const TextStyle(color: AppColors.darkTextSecondary, fontSize: 12)),
          const SizedBox(height: 16),
          GestureDetector(
            onTap: () => setState(() => _flashcardFlipped = !_flashcardFlipped),
            child: AnimatedContainer(
              duration: const Duration(milliseconds: 300),
              width: double.infinity,
              constraints: const BoxConstraints(minHeight: 180),
              padding: const EdgeInsets.all(20),
              decoration: BoxDecoration(
                gradient: LinearGradient(
                  colors: _flashcardFlipped ? [const Color(0xFF00C49A), const Color(0xFF006B54)] : [const Color(0xFF6C63FF), const Color(0xFF3D35CC)],
                  begin: Alignment.topLeft, end: Alignment.bottomRight,
                ),
                borderRadius: BorderRadius.circular(16),
              ),
              child: Column(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  Text(_flashcardFlipped ? 'Answer' : 'Question', style: const TextStyle(color: Colors.white60, fontSize: 12, fontWeight: FontWeight.w600)),
                  const SizedBox(height: 12),
                  Text(_flashcardFlipped ? (card['answer'] ?? '') : (card['question'] ?? ''), textAlign: TextAlign.center, style: const TextStyle(color: Colors.white, fontSize: 16, fontWeight: FontWeight.w600, height: 1.5)),
                  if (!_flashcardFlipped) const SizedBox(height: 12),
                  if (!_flashcardFlipped) const Text('Tap to reveal answer', style: TextStyle(color: Colors.white54, fontSize: 11)),
                ],
              ),
            ),
          ),
          const SizedBox(height: 20),
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceEvenly,
            children: [
              IconButton(icon: const Icon(Icons.arrow_back_ios_rounded, color: Colors.white70), onPressed: _flashcardIndex > 0 ? () => setState(() { _flashcardIndex--; _flashcardFlipped = false; }) : null),
              ElevatedButton.icon(onPressed: () => _runAiAction('flashcards'), icon: const Icon(Icons.refresh_rounded, size: 16), label: const Text('Regenerate'), style: ElevatedButton.styleFrom(backgroundColor: AppColors.primary, padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 8))),
              IconButton(icon: const Icon(Icons.arrow_forward_ios_rounded, color: Colors.white70), onPressed: _flashcardIndex < _flashcards.length - 1 ? () => setState(() { _flashcardIndex++; _flashcardFlipped = false; }) : null),
            ],
          ),
        ],
      ),
    );
  }

  Widget _buildQuizTab() {
    if (_quiz.isEmpty) {
      return Center(
        child: Column(mainAxisAlignment: MainAxisAlignment.center, children: [
          const Text('❓', style: TextStyle(fontSize: 48)),
          const SizedBox(height: 12),
          const Text('No quiz yet', style: TextStyle(color: Colors.white, fontSize: 16)),
          const SizedBox(height: 8),
          ElevatedButton.icon(onPressed: () => _runAiAction('quiz'), icon: const Icon(Icons.auto_awesome), label: const Text('Generate Quiz'), style: ElevatedButton.styleFrom(backgroundColor: AppColors.primary)),
        ]),
      );
    }
    final q = _quiz[_quizIndex];
    final options = List<String>.from(q['options'] ?? ['True', 'False']);
    final correct = q['answer'] ?? '';

    return SingleChildScrollView(
      padding: const EdgeInsets.all(16),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(children: [
            Text('Q ${_quizIndex + 1}/${_quiz.length}', style: const TextStyle(color: AppColors.darkTextSecondary, fontSize: 12)),
            const Spacer(),
            Container(padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 3), decoration: BoxDecoration(color: AppColors.accent.withValues(alpha: 0.1), borderRadius: BorderRadius.circular(8)), child: Text(q['type'] ?? 'mcq', style: const TextStyle(color: AppColors.accent, fontSize: 10))),
          ]),
          const SizedBox(height: 12),
          Text(q['question'] ?? '', style: const TextStyle(color: Colors.white, fontSize: 15, fontWeight: FontWeight.w600, height: 1.5)),
          const SizedBox(height: 16),
          ...options.map((opt) {
            final isSelected = _quizSelected == opt;
            final isCorrect = opt == correct;
            Color borderColor = AppColors.darkBorder;
            Color bgColor = const Color(0xFF1A1A2E);
            if (_quizShowAnswer) {
              if (isCorrect) { borderColor = AppColors.success; bgColor = AppColors.success.withValues(alpha: 0.1); }
              else if (isSelected && !isCorrect) { borderColor = AppColors.danger; bgColor = AppColors.danger.withValues(alpha: 0.1); }
            } else if (isSelected) {
              borderColor = AppColors.primary;
              bgColor = AppColors.primary.withValues(alpha: 0.1);
            }
            return GestureDetector(
              onTap: _quizShowAnswer ? null : () => setState(() => _quizSelected = opt),
              child: Container(
                margin: const EdgeInsets.only(bottom: 8),
                padding: const EdgeInsets.all(12),
                decoration: BoxDecoration(color: bgColor, borderRadius: BorderRadius.circular(10), border: Border.all(color: borderColor)),
                child: Text(opt, style: TextStyle(color: _quizShowAnswer && isCorrect ? Colors.white : Colors.white70, fontWeight: _quizShowAnswer && isCorrect ? FontWeight.w600 : FontWeight.normal, fontSize: 13)),
              ),
            );
          }),
          const SizedBox(height: 12),
          if (!_quizShowAnswer)
            SizedBox(width: double.infinity, child: ElevatedButton(onPressed: _quizSelected != null ? () => setState(() => _quizShowAnswer = true) : null, style: ElevatedButton.styleFrom(backgroundColor: AppColors.primary), child: const Text('Check Answer')))
          else ...[
            if (q['explanation'] != null)
              Container(padding: const EdgeInsets.all(12), decoration: BoxDecoration(color: AppColors.success.withValues(alpha: 0.05), borderRadius: BorderRadius.circular(10), border: Border.all(color: AppColors.success.withValues(alpha: 0.3))), child: Text('💡 ${q['explanation']}', style: const TextStyle(color: Colors.white70, fontSize: 12, height: 1.4))),
            const SizedBox(height: 10),
            Row(children: [
              if (_quizIndex < _quiz.length - 1)
                Expanded(child: ElevatedButton(onPressed: () => setState(() { _quizIndex++; _quizSelected = null; _quizShowAnswer = false; }), style: ElevatedButton.styleFrom(backgroundColor: AppColors.primary), child: const Text('Next Question'))),
              if (_quizIndex == _quiz.length - 1)
                Expanded(child: ElevatedButton(onPressed: () => setState(() { _quizIndex = 0; _quizSelected = null; _quizShowAnswer = false; }), style: ElevatedButton.styleFrom(backgroundColor: AppColors.success), child: const Text('Restart Quiz'))),
            ]),
          ],
        ],
      ),
    );
  }

  Widget _buildRoadmapTab() {
    if (_roadmap.isEmpty) {
      return Center(
        child: Column(mainAxisAlignment: MainAxisAlignment.center, children: [
          const Text('🗺️', style: TextStyle(fontSize: 48)),
          const SizedBox(height: 12),
          const Text('No roadmap yet', style: TextStyle(color: Colors.white, fontSize: 16)),
          const SizedBox(height: 8),
          ElevatedButton.icon(onPressed: () => _runAiAction('roadmap'), icon: const Icon(Icons.auto_awesome), label: const Text('Generate Roadmap'), style: ElevatedButton.styleFrom(backgroundColor: AppColors.primary)),
        ]),
      );
    }
    return SingleChildScrollView(
      padding: const EdgeInsets.all(16),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(children: [
            const Text('🗺️ Study Roadmap', style: TextStyle(color: Colors.white, fontSize: 16, fontWeight: FontWeight.w700)),
            const Spacer(),
            GestureDetector(onTap: () => _runAiAction('roadmap'), child: const Icon(Icons.refresh_rounded, size: 18, color: AppColors.accent)),
          ]),
          const SizedBox(height: 12),
          ..._roadmap.split('\n').map((line) {
            if (line.startsWith('## ')) return Padding(padding: const EdgeInsets.only(top: 12, bottom: 4), child: Text(line.substring(3), style: const TextStyle(color: AppColors.primary, fontSize: 14, fontWeight: FontWeight.w700)));
            if (line.startsWith('# ')) return Padding(padding: const EdgeInsets.only(top: 8, bottom: 4), child: Text(line.substring(2), style: const TextStyle(color: Colors.white, fontSize: 16, fontWeight: FontWeight.w800)));
            if (line.startsWith('- ')) return Padding(padding: const EdgeInsets.only(bottom: 4), child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [const Text('→ ', style: TextStyle(color: AppColors.accent)), Expanded(child: Text(line.substring(2), style: const TextStyle(color: Colors.white70, fontSize: 13, height: 1.4)))]));
            return Padding(padding: const EdgeInsets.only(bottom: 4), child: Text(line, style: const TextStyle(color: Colors.white60, fontSize: 13, height: 1.4)));
          }),
        ],
      ),
    );
  }

  Widget _buildStatusBar() {
    final readingTime = (_wordCount / 200).ceil();
    return Container(
      height: 28,
      padding: const EdgeInsets.symmetric(horizontal: 16),
      decoration: const BoxDecoration(border: Border(top: BorderSide(color: AppColors.darkBorder))),
      child: Row(
        children: [
          Text('$_wordCount words', style: const TextStyle(color: AppColors.darkTextSecondary, fontSize: 11)),
          const Text(' · ', style: TextStyle(color: AppColors.darkBorder)),
          Text('~$readingTime min read', style: const TextStyle(color: AppColors.darkTextSecondary, fontSize: 11)),
          const Text(' · ', style: TextStyle(color: AppColors.darkBorder)),
          Text(_noteType.toUpperCase(), style: const TextStyle(color: AppColors.accent, fontSize: 11, fontWeight: FontWeight.w600)),
          const Spacer(),
          if (_saving) const Text('Saving...', style: TextStyle(color: AppColors.darkTextSecondary, fontSize: 11))
          else const Text('Auto-save on', style: TextStyle(color: AppColors.success, fontSize: 11)),
        ],
      ),
    );
  }

  Widget _buildMobileBottom() {
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 6),
      decoration: const BoxDecoration(border: Border(top: BorderSide(color: AppColors.darkBorder))),
      child: Row(
        children: [
          Text('$_wordCount words', style: const TextStyle(color: AppColors.darkTextSecondary, fontSize: 11)),
          const Spacer(),
          TextButton.icon(
            onPressed: () => showModalBottomSheet(context: context, isScrollControlled: true, backgroundColor: const Color(0xFF1E1E2E), shape: const RoundedRectangleBorder(borderRadius: BorderRadius.vertical(top: Radius.circular(20))), builder: (ctx) => SizedBox(height: MediaQuery.of(ctx).size.height * 0.85, child: _buildAiPanel())),
            icon: const Icon(Icons.auto_awesome, size: 16, color: AppColors.accent),
            label: const Text('AI Panel', style: TextStyle(color: AppColors.accent, fontSize: 13)),
          ),
        ],
      ),
    );
  }
}
