import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutter_animate/flutter_animate.dart';
import '../bloc/plan_bloc.dart';
import '../../../core/theme/app_theme.dart';
import '../../../shared/widgets/owl_button.dart';
import '../../../shared/models/models.dart';
import '../../../shared/services/link_launcher.dart';
import '../../../core/constants/hive_keys.dart';

class PlanScreen extends StatefulWidget {
  const PlanScreen({super.key});
  @override State<PlanScreen> createState() => _PlanScreenState();
}

class _PlanScreenState extends State<PlanScreen> {
  @override
  void initState() {
    super.initState();
    context.read<PlanBloc>().add(const PlanLoadRequested());
  }

  @override
  Widget build(BuildContext context) {
    final isDark = Theme.of(context).brightness == Brightness.dark;
    return Scaffold(
      backgroundColor: isDark ? AppColors.darkBg : AppColors.lightBg,
      appBar: AppBar(
        title: const Text("Today's Plan"),
        actions: [
          TextButton.icon(
            onPressed: () => context.read<PlanBloc>().add(PlanAutoGenerateRequested()),
            icon: const Icon(Icons.auto_awesome, color: AppColors.primary, size: 18),
            label: const Text('Auto-Generate', style: TextStyle(color: AppColors.primary, fontSize: 12)),
          ),
        ],
      ),
      body: BlocBuilder<PlanBloc, PlanState>(
        builder: (context, state) {
          if (state.status == PlanStatus.loading) {
            return const Center(child: CircularProgressIndicator(color: AppColors.primary));
          }

          final plan = state.plan;

          return Column(children: [
            // ─── Progress Header ──────────────────────────────
            if (plan != null) _PlanProgress(plan: plan),

            // ─── Task List ────────────────────────────────────
            Expanded(
              child: plan == null || plan.tasks.isEmpty
                ? _EmptyPlan(onAutoGenerate: () => context.read<PlanBloc>().add(PlanAutoGenerateRequested()))
                : ListView.builder(
                    padding: const EdgeInsets.all(AppSpacing.md),
                    itemCount: plan.tasks.length,
                    itemBuilder: (_, i) => _TaskCard(
                      task: plan.tasks[i],
                      onToggle: (v) => context.read<PlanBloc>().add(PlanTaskToggled(plan.tasks[i].id, v)),
                      onDelete: () => context.read<PlanBloc>().add(PlanTaskDeleted(plan.tasks[i].id)),
                    ).animate(delay: (i * 50).ms).fadeIn().slideX(begin: 0.3),
                  ),
            ),
          ]);
        },
      ),
      floatingActionButton: FloatingActionButton.extended(
        onPressed: () => _showAddTaskSheet(context),
        backgroundColor: AppColors.primary,
        icon: const Icon(Icons.add, color: Colors.white),
        label: const Text('Add Task', style: TextStyle(color: Colors.white)),
      ),
    );
  }

  void _showAddTaskSheet(BuildContext ctx) {
    showModalBottomSheet(
      context: ctx,
      isScrollControlled: true,
      backgroundColor: Colors.transparent,
      builder: (_) => BlocProvider.value(
        value: ctx.read<PlanBloc>(),
        child: const _AddTaskSheet(),
      ),
    );
  }
}

class _PlanProgress extends StatelessWidget {
  final TodoPlanModel plan;
  const _PlanProgress({required this.plan});

  @override
  Widget build(BuildContext context) {
    return Container(
      margin: const EdgeInsets.all(16),
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        gradient: AppColors.primaryGradient,
        borderRadius: BorderRadius.circular(AppRadius.lg),
        boxShadow: AppShadow.glow,
      ),
      child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
        Row(children: [
          Expanded(child: Text(plan.title, style: const TextStyle(color: Colors.white, fontWeight: FontWeight.w700, fontSize: 16))),
          if (plan.isAutoGenerated)
            Container(padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 3),
              decoration: BoxDecoration(color: Colors.white.withValues(alpha: 0.2), borderRadius: BorderRadius.circular(AppRadius.round)),
              child: const Text('AI Generated', style: TextStyle(color: Colors.white, fontSize: 10, fontWeight: FontWeight.w600))),
        ]),
        const SizedBox(height: 8),
        Text('${plan.completedCount}/${plan.tasks.length} tasks completed', style: TextStyle(color: Colors.white.withValues(alpha: 0.85), fontSize: 13)),
        const SizedBox(height: 10),
        ClipRRect(
          borderRadius: BorderRadius.circular(AppRadius.round),
          child: LinearProgressIndicator(value: plan.progress, minHeight: 6, backgroundColor: Colors.white.withValues(alpha: 0.2), valueColor: const AlwaysStoppedAnimation(Colors.white)),
        ),
        if (plan.progress >= 1.0) ...[
          const SizedBox(height: 8),
          const Text('🎉 Daily goal completed! +30 XP', style: TextStyle(color: Colors.white, fontWeight: FontWeight.w600)),
        ],
      ]),
    );
  }
}

class _TaskCard extends StatelessWidget {
  final TodoTask task;
  final Function(bool) onToggle;
  final VoidCallback onDelete;
  const _TaskCard({required this.task, required this.onToggle, required this.onDelete});

  Color get _priorityColor => task.priority == 'high' ? AppColors.danger : task.priority == 'medium' ? AppColors.warning : AppColors.success;

  @override
  Widget build(BuildContext context) {
    final isDark = Theme.of(context).brightness == Brightness.dark;
    return AnimatedContainer(
      duration: 200.ms,
      margin: const EdgeInsets.only(bottom: 10),
      padding: const EdgeInsets.all(14),
      decoration: BoxDecoration(
        color: task.isCompleted ? (isDark ? AppColors.darkSurface : Colors.grey.shade50) : (isDark ? AppColors.darkCard : Colors.white),
        borderRadius: BorderRadius.circular(AppRadius.md),
        border: Border.all(color: task.isCompleted ? AppColors.success.withValues(alpha: 0.3) : (isDark ? AppColors.darkBorder : Colors.grey.shade200)),
      ),
      child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [
        GestureDetector(
          onTap: () => onToggle(!task.isCompleted),
          child: AnimatedContainer(
            duration: 200.ms,
            width: 22, height: 22,
            decoration: BoxDecoration(
              color: task.isCompleted ? AppColors.success : Colors.transparent,
              border: Border.all(color: task.isCompleted ? AppColors.success : AppColors.darkBorder, width: 2),
              borderRadius: BorderRadius.circular(6),
            ),
            child: task.isCompleted ? const Center(child: Icon(Icons.check, size: 14, color: Colors.white)) : null,
          ),
        ),
        const SizedBox(width: 12),
        Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
          Text(task.text,
            style: Theme.of(context).textTheme.bodyMedium?.copyWith(
              decoration: task.isCompleted ? TextDecoration.lineThrough : null,
              color: task.isCompleted ? AppColors.darkTextSecondary : (isDark ? Colors.white : AppColors.lightText),
              fontWeight: FontWeight.w500,
            ),
            maxLines: 2, overflow: TextOverflow.ellipsis),
          const SizedBox(height: 4),
          Row(children: [
            if (task.platform.isNotEmpty) Text(task.platform, style: const TextStyle(color: AppColors.darkTextSecondary, fontSize: 11)),
            if (task.platform.isNotEmpty) const SizedBox(width: 8),
            Container(width: 6, height: 6, decoration: BoxDecoration(color: _priorityColor, shape: BoxShape.circle)),
            const SizedBox(width: 4),
            Text('${task.priority} priority', style: TextStyle(color: _priorityColor, fontSize: 11)),
            if (task.estimatedMinutes > 0) ...[
              const SizedBox(width: 8),
              Text('~${task.estimatedMinutes}m', style: const TextStyle(color: AppColors.darkTextSecondary, fontSize: 11)),
            ],
          ]),
        ])),
        Column(children: [
          if (task.link.isNotEmpty)
            IconButton(onPressed: () => LinkLauncher.open(task.link), icon: const Icon(Icons.open_in_new, size: 16, color: AppColors.accent), constraints: const BoxConstraints(), padding: EdgeInsets.zero),
          IconButton(onPressed: onDelete, icon: const Icon(Icons.delete_outline, size: 16, color: AppColors.danger), constraints: const BoxConstraints(), padding: const EdgeInsets.only(top: 4)),
        ]),
      ]),
    );
  }
}

class _EmptyPlan extends StatelessWidget {
  final VoidCallback onAutoGenerate;
  const _EmptyPlan({required this.onAutoGenerate});

  @override
  Widget build(BuildContext context) {
    return Center(child: Column(mainAxisAlignment: MainAxisAlignment.center, children: [
      const Text('📅', style: TextStyle(fontSize: 60)),
      const SizedBox(height: 16),
      Text("No plan for today yet", style: Theme.of(context).textTheme.titleMedium?.copyWith(color: Colors.white)),
      const SizedBox(height: 8),
      const Text('Let AI generate a personalized plan based on your weak topics', textAlign: TextAlign.center, style: TextStyle(color: AppColors.darkTextSecondary)),
      const SizedBox(height: 24),
      OwlButton(label: '✨ Auto-Generate Plan', onTap: onAutoGenerate, width: 220),
    ]));
  }
}

class _AddTaskSheet extends StatefulWidget {
  const _AddTaskSheet();
  @override State<_AddTaskSheet> createState() => _AddTaskSheetState();
}

class _AddTaskSheetState extends State<_AddTaskSheet> {
  final _textCtrl = TextEditingController();
  final _linkCtrl = TextEditingController();
  String _platform = 'LeetCode', _priority = 'medium';
  final int _minutes = 30;

  @override
  Widget build(BuildContext context) {
    final isDark = Theme.of(context).brightness == Brightness.dark;
    return Container(
      decoration: BoxDecoration(color: isDark ? AppColors.darkCard : Colors.white, borderRadius: const BorderRadius.vertical(top: Radius.circular(20))),
      padding: EdgeInsets.only(left: 20, right: 20, top: 20, bottom: MediaQuery.of(context).viewInsets.bottom + 20),
      child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [
        Text('Add Task', style: Theme.of(context).textTheme.titleLarge?.copyWith(fontWeight: FontWeight.w700, color: isDark ? Colors.white : AppColors.lightText)),
        const SizedBox(height: 16),
        TextFormField(controller: _textCtrl, style: TextStyle(color: isDark ? Colors.white : AppColors.lightText), decoration: const InputDecoration(labelText: 'Task description')),
        const SizedBox(height: 12),
        TextFormField(controller: _linkCtrl, style: TextStyle(color: isDark ? Colors.white : AppColors.lightText), decoration: const InputDecoration(labelText: 'Link (optional)')),
        const SizedBox(height: 12),
        Row(children: [
          Expanded(child: DropdownButtonFormField<String>(initialValue: _priority, onChanged: (v) => setState(() => _priority = v!),
            style: TextStyle(color: isDark ? Colors.white : AppColors.lightText), dropdownColor: isDark ? AppColors.darkCard : Colors.white,
            decoration: const InputDecoration(labelText: 'Priority'),
            items: ['low','medium','high'].map((p) => DropdownMenuItem(value: p, child: Text(p[0].toUpperCase() + p.substring(1), style: TextStyle(color: isDark ? Colors.white : AppColors.lightText)))).toList())),
          const SizedBox(width: 12),
          Expanded(child: DropdownButtonFormField<String>(initialValue: _platform, onChanged: (v) => setState(() => _platform = v!),
            style: TextStyle(color: isDark ? Colors.white : AppColors.lightText), dropdownColor: isDark ? AppColors.darkCard : Colors.white,
            decoration: const InputDecoration(labelText: 'Platform'),
            items: AppConstants.platforms.map((p) => DropdownMenuItem(value: p, child: Text(p, style: TextStyle(color: isDark ? Colors.white : AppColors.lightText)))).toList())),
        ]),
        const SizedBox(height: 16),
        OwlButton(label: 'Add Task', onTap: _textCtrl.text.isNotEmpty ? _submit : null),
      ]),
    );
  }

  void _submit() {
    if (_textCtrl.text.trim().isEmpty) return;
    context.read<PlanBloc>().add(PlanTaskAdded({'text': _textCtrl.text.trim(), 'platform': _platform, 'priority': _priority, 'link': _linkCtrl.text.trim(), 'estimatedMinutes': _minutes}));
    Navigator.pop(context);
  }
}
